### ISSUE TITLE
proposal: Lock issues(?)

### ISSUE THREAD

**Issue by Andre601** [peaceiris/actions-label-commenter#308]
**Is your feature request related to a problem? Please describe.**
I'm unable to find an option in the label-commenter-config.yml to lock an issue in order to prevent things like Spam or similar, which makes me assume that this Action doesn't have such an option to begin with.

**Describe the solution you'd like**
It would be nice to have the option, to also lock an issue alongside closing it.
the actions could simply be called `lock` and `unlock` and perhaps an additional option to set the reason for why it was locked could be added too.

Examples:
```yaml
labels:
  # User spammed an issue and comments
  - name: 'Locked (Spam)'
    labeled:
      issue:
        body: |-
          This issue has been **LOCKED** because of spam!
          
          Please do not spam messages and/or issues on the issue tracker. You may get blocked from this repository for doing so.
        action: 'lock'
        reason: 'spam'
  # User send very heated (aggressive) messages
  - name: 'Locked (Heated Chat)'
    labeled:
      issue:
        body: |-
          This issue has been **LOCKED** because of heated conversation!
          
          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        action: 'lock'
        reason: 'heated'
  # Issue was completely off-topic or messages where not about the issue itself
  - name: 'Locked (Off-topic)'
    labeled:
      issue:
        body: |-
          This issue has been **LOCKED** because of Off-topic conversations!
          
          While we do appreciate conversations in issues would we like to keep them on the topic of the issue.
          Please use our other means of communication for casual chats.
        action: 'lock'
        reason: 'off-topic'
  # Issue was resolved and future messages should be avoided
  - name: 'Locked (Resolved)'
    labeled:
      issue:
        body: |-
          This issue has been **LOCKED** because of it being resolved!
          
          The issue has been fixed and is therefore considered resolved.
          If you still encounter this or it has changed, open a new issue instead of responding to solved ones.
        action: 'lock'
        reason: 'resolved'
```

GitHub does offer the above 4 reasons (Off-topic, Too Heated, Resolved and Spam) when locking an issue which is optional.

**Describe alternatives you've considered**
The only option is a manual lock of the issue.

**Additional context**
