### ISSUE TITLE
proposal: Comment header and footer

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-label-commenter#318]
**Is your feature request related to a problem? Please describe.**

This was suggested by @Andre601 at https://github.com/peaceiris/actions-label-commenter/issues/308#issuecomment-733168251

**Describe the solution you'd like**

```yaml
# .github/label-commenter-config.yml

comment:
  header: Hi, there.
  footer: >-
    > This is an automated comment created by the [actions-label-commenter](https://github.com/peaceiris/actions-label-commenter).
    Responding to the bot or mentioning it won't have any effect.

labels:
...
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A
