### ISSUE TITLE
proposal: v2 Fetch config file internally without actions/checkout

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-label-commenter#447]
**Is your feature request related to a problem? Please describe.**

- Fetch the config file at `config_file` from the remote repository.

### v2 Workflow

```yaml
name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v2
#       with:
#         config_file: '.github/label-commenter-config.yml'
```

```diff
- - uses: actions/checkout@v2
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- https://github.com/actions/labeler/blob/v3.0.2/src/labeler.ts
- [How to Write an Async Class Constructor in TypeScript or JavaScript | by Gabe Szczepanek | Better Programming](https://betterprogramming.pub/how-to-write-an-async-class-constructor-in-typescript-javascript-7d7e8325c35e)
