### ISSUE TITLE
proposal: Improve and simplify config format

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-label-commenter#449]
### Discussed in https://github.com/peaceiris/actions-label-commenter/discussions/445

<div type='discussions-op-text'>

<sup>Originally posted by **Andre601** June 16, 2021</sup>
I feel like the config is kind of bloated in some sections and could receive a improvement.

For example do I see no reason for having a `lock` option when the only goal for it is to have `lock` and `unlock` as options. This could just be an option for the `action` field and result in close + lock or open + unlock.

Another thing that could also be something to improve is the comment option.
This one could be changed to something like this:
```yaml
comment: |-
  Hello,
  {{ content }}
  This is an automated comment created by a [GitHub Action](https://github.com/peaceiris/actions-label-commenter).
  Responding to or mentioning it has no effect.
```
The `{{ content }}` placeholder would then be replaced with whatever you defined in the corresponding `body` section of a label.</div>

**Comment by Andre601** [comment]
I have suggestions for 2 possible ideas on how to restructure the file handling, which both have benefits but also disadvantages.

## 1) Split types up into separate files
Perhaps it could be worth it to split up issues, PRs and discussions into separate files under a `label-commenter` folder (i.e. `.github/label-commenter/issue.yml` for issue-related comments).

### Benefits
- Gets rid of the `issue`, `pr` and `discussion` sections used for each label.

### Downsides
- 3 times the files you have to maintain both as action or user of it.
- No easy way to apply header or footer (common parts) to it. Would probs require a 4th file for it.

## 2) Separate MD file per label
Maybe giving each label a own Markdown file could be the way to go.
The settings could then be applied through YAML frontmatter, allowing pretty much the same level of control you currently have + some more.

Example file named `spam.md`:
```markdown
---
support: # List of types this action should reply to
- issue
- pull_request
- discussion

# Used to "close", "open", "lock" or "unlock"
action: 'lock'
reason: 'spam' # Used when "lock" is set as action

# Settings to exclude Header/Footer
exclude_header: false
exclude_footer: false
---
## 🔒 LOCKED
This {{ type }} has been **locked** <!-- Maybe a new "{{ type }}" placeholder returning the type? (Issue, Pull request or Discussion) -->
Reason: Spam.
```

### Benefits
- Much easier file-setup for the end-user (Doesn't need to make sure YAML formatting is correct with exception of frontmatter part)
- Better control about actions.

### Downsides
- Not all label formats/names may be supported (i.e. emojis). Is `:` f.e. supported in file names?
  - Would probably require some work-arounds (label sanitization?) to make it work with more special labels.
- Requires more advanced file handling (1 file per label is a lot)
- YAML Frontmatter handling. Not sure how hard or easy this would be.

----
If I had to choose would I honestly go with the second option.

**Comment by peaceiris** [comment]
Those are interesting. But we should consider using the YAML anchor/alias at first.

```yaml
labels:
  - name: locked (spam)
    labeled:
      issue:
        body: &locked_spam_body |
          This issue has been **LOCKED** because of spam!

          Please do not spam messages on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: *locked_spam_body
        action: close
        locking: lock
        lock_reason: spam
      discussion:
        body: *locked_spam_body
        locking: lock
        lock_reason: spam
```
