### ISSUE TITLE
support: load config from external repository

### ISSUE THREAD

**Issue by alombarte** [peaceiris/actions-label-commenter#618]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Hi,

I was testing the action and I got the impression that the configuration file is always assumed to live inside the repository whose job is calling the action. When using the special `.github` repository (not folder) along with the [health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) and other cross-organization workflows, the action fails to load the configuration.

For instance, in your github.com/ORGANIZATION/.github repository, you have a file `github.com/ORGANIZATION/.github/.github/workflows/label-commenter.yml` with content:
```
name: Label Commenter

on:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
```
The `on` specifies the calling from outside. And then you have the config in its default location, also inside the `.github` repo. Then you call it from another repo (github.com/ORGANIZATION/some-repo) with its workflow:

```
name: Label commenter
on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
jobs:
  stale:
    uses: ORGANIZATION/.github/.github/workflows/label-commenter.yml@main
```

The configuration file will fail to load as it is looking from within the calling repo, but the config lives centralized with the label commenter action.

Is there a way to specify a different organization and repo to load the configuration file, or to load it embedded using `with` or similar in one file?

Thank you!

### Relevant links

```markdown
YAML config: https://github.com/krakendio/.github/blob/48caa81a3c9159759f064976665631d6f5e9bb83/.github/label-commenter-config.yml
YAML workflow: https://github.com/krakendio/krakend-schema/blob/1dd2ccfe75bcfb7778a1340f0ef413da93a368ef/.github/workflows/labels.yml
```

### Relevant log output

`Action failed with error "not found .github/label-commenter-config.yml"`

**Comment by alombarte** [comment]
Hi @peaceiris, I see your :eyes: reaction to the issue, but I am not very good at analyzing emoji reactions. Is there something unclear or questions you have about it? 

I think this action is very useful (thank you for that!), and the ability to use it centralized for all repos of an organization would be awesome.

**Comment by peaceiris** [comment]
Thank you for your great suggestion!

A few months ago, I considered remaking the config_file input to fetch a custom remote config file like https://github.com/actions/labeler. That was the plan in my mind. It can satisfy your demand.

I will work on this in the next major version v2 https://github.com/peaceiris/actions-label-commenter/milestone/2

**Comment by peaceiris** [comment]
The new config_file has been already implemented, but not released.
You can try it with c2d00660c86f2b9ed0fb35b372c451558eba85b3.

https://github.com/peaceiris/actions-label-commenter/blob/2e98b600133feca59c911148759c7af4d7022a42/src/classes/config.ts#L125

https://github.com/peaceiris/actions-label-commenter/blob/2e98b600133feca59c911148759c7af4d7022a42/.github/workflows/label-commenter.yml#L27

**Comment by peaceiris** [comment]
Ahh, maybe the called workflow runs on krakendio/krakend-schema, not krakendio/.github

I will add support fetching a file with the HTTPS protocol for that case.

```yaml
      - uses: peaceiris/actions-label-commenter@v2
        with:
          config_file: https://github.com/krakendio/.github/blob/main/.github/label-commenter-config.yml
          # or config_file: https://raw.githubusercontent.com/krakendio/.github/main/.github/label-commenter-config.yml
```
