### ISSUE TITLE
proposal: Option to ignore users

### ISSUE THREAD

**Issue by Andre601** [peaceiris/actions-label-commenter#854]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

A new option to set a list of users the Action should ignore when running.

Depending on how difficult this could be, should support for teams be considered too, to ignore people of a specific team.

### Describe the solution you'd like

The config option would be a string (Given github actions doesn't support anything else really) where each name is space-separated(?)

Example:
```yaml
# All the actions stuff

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Comment
        uses: peaceiris/actions-label-commenter@v1
        with:
          ignored_users: |
            Someone
            @some-team # Maybe as a team format? Or just like name?
```

### Describe alternatives you've considered

Only alternative I could consider is setting up some evaluation that checks the users first to then skip steps, which is rather complicated for me to figure out.
